language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip3 install -r requirements.txt
script:
    - /usr/bin/python3 --version
    - which python
    - pytest
    - cp examples/* .; pwd
    - python client-simple.py
    - python client-twisted.py
